---
- hosts: pve_servers
  become: true
  pre_tasks:
  - name: Ensure enterprise Ceph apt repository is absent
    ansible.builtin.apt_repository:
      repo: deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise
      state: absent
      filename: ceph

  - name: Ensure non-enterprise Ceph apt repository is present
    ansible.builtin.apt_repository:
      repo: deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription
      state: present
      filename: ceph

  - name: Ensure enterprise Proxmox apt repositories is absent
    ansible.builtin.apt_repository:
      repo: deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise
      state: absent
      filename: pve-enterprise

  - name: Ensure non-enterprise Proxmox apt repositories are present
    ansible.builtin.apt_repository:
      repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
      state: present

- hosts: all
  become: true
  pre_tasks:
  - name: Ensure packages updated
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution in ['Debian', 'Ubuntu']

  tasks:
  - name: Ensure common packages are installed
    apt:
      name:
      - vim
      state: present

- hosts: maas_controllers
  become: true
  roles:
  - maas_controller

- hosts: file_servers
  become: true
  roles:
  - cockpit-nas

- hosts: k8s_staging
  roles: 
  - role: ansible_role_microk8s
    vars:
      microk8s_version: 1.28/stable
      microk8s_plugins:
        community: true
        dns: true
        ha-cluster: true
        helm: true
        helm3: true
        ingress: true
        registry: true
        rook-ceph: true
