---
- name: Fail if running on unsupported distribution
  fail:
    msg: NextCloud role only supported on Debian or Ubuntu
  when: ansible_distribution not in ["Debian", "Ubuntu"]

- name: Ensure NextCloud snap package installed
  community.general.snap: 
    name: nextcloud
    state: present
  register: nextcloud_install_check

- name: Ensure NextCloud snap plug is connected
  changed_when: false
  shell: 'snap connect {{ item.app }}:{{ item.plug }}'
  with_items:
    - plug: removable-media
      app: nextcloud

# https://github.com/nextcloud-snap/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition
- name: Ensure NextCloud mnt directory has correct permissions
  ansible.builtin.file:
    path: /mnt/nextcloud
    state: directory
    mode: '0770'
    owner: root
    group: root

- name: Ensure NextCloud dataset present
  community.general.zfs:
    name: "{{nextcloud_dataset}}"
    state: present
    extra_zfs_properties:
      quota: "{{nextcloud_dataset_quota}}"
      mountpoint: /mnt/nextcloud
  register: nextcloud_dataset

- name: Ensure the NextCloud config file exists
  ansible.builtin.wait_for:
    path: /var/snap/nextcloud/current/nextcloud/config/autoconfig.php
  when: nextcloud_install_check.changed

# Next, wait for the config file to exist (this may take time if NextCloud was just installed)
- name: Ensure NextCloud auto-configuration installed
  template:
    src: templates/autoconfig.php.j2
    dest: /var/snap/nextcloud/current/nextcloud/config/autoconfig.php
  register: configuration
  when: nextcloud_install_check.changed

- name: Ensure NextCloud restarted if data directory or configuration changed
  service: 
    name: snap.nextcloud.php-fpm.service
    state: restarted
  when: nextcloud_install_check.changed or nextcloud_dataset.changed or configuration.changed or autoconfig_removed.changed
