---
- name: Fail if running on unsupported distribution
  fail:
    msg: NextCloud role only supported on Debian or Ubuntu
  when: ansible_distribution not in ["Debian", "Ubuntu"]

- name: Ensure NextCloud dataset present
  community.general.zfs:
    name: "{{nextcloud_dataset}}"
    state: present
    extra_zfs_properties:
      quota: "{{nextcloud_dataset_quota}}"
  register: nextcloud_dataset

- name: Ensure Podman package present
  apt:
    name: podman=3.4.4+ds1-1ubuntu1
    state: present
    allow_downgrade: true
  changed_when: false

- name: Ensure the NextCloud network exists
  containers.podman.podman_network:
    name: nextcloud_network
    state: present

- name: Ensure the NextCloud pod exists
  containers.podman.podman_pod:
    name: nextcloud_pod
    network: nextcloud_network
    state: started

- name: Ensure MariaDB volume directory exists
  ansible.builtin.file:
    path: "{{nextcloud_dataset_dir}}/mariadb"
    state: directory

- name: Ensure MariaDB container is running
  containers.podman.podman_container:
    name: mariadb
    state: started
    pod: nextcloud_pod
    image: docker.io/library/mariadb:lts
    network: nextcloud_network
    env:
      MYSQL_ROOT_PASSWORD: "{{mysql_root_password}}"
      MYSQL_PASSWORD: "{{mysql_nextcloud_password}}"
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    volume:
    - "{{nextcloud_dataset_dir}}/mariadb:/var/lib/mysql"

- name: Ensure NextCloud volume directory exists
  ansible.builtin.file:
    path: "{{nextcloud_dataset_dir}}/nextcloud"
    state: directory

- name: Ensure NextCloud container is running
  containers.podman.podman_container:
    name: nextcloud
    state: started
    pod: nextcloud_pod
    image: docker.io/library/nextcloud:26-apache
    network: nextcloud_network
    ports:
    - "8080:80"
    env:
      MYSQL_HOST: mariadb
      MYSQL_PASSWORD: "{{mysql_nextcloud_password}}"
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      TRUSTED_PROXIES: "{{nextcloud_trusted_proxy}}"
      OVERWRITECLIURL: "{{nextcloud_overwritecliurl}}"
      OVERWRITEPROTOCOL: "https"
    volume:
    - "{{nextcloud_dataset_dir}}/nextcloud:/var/www/html"
